### ISSUE TITLE
Nested templates

### ISSUE THREAD

**Issue by rasstislav** [satrun77/silverstripe-template-tags#5]
Hello,

are nested templates with set blocks also supported? It's not working right for me.

ex.:
```
<% template TemplateName %>
    <% set Header %>
        <h1>Hello world</h1>
    <% end_set %>
    <% set Body %>
        <% template AnotherTemplateName %>
            <% set AnotherHeader %>
                <h2>Hello world</h2>
            <% end_set %>
        <% end_template %>
    <% end_set %>
<% end_template %>
```

**Comment by satrun77** [comment]
I haven't tested this. But it might be a nice feature to add. If you want you can create a PR. I will try to do it next next few weeks

You may be able to do this if this works for you
```
<% template TemplateName %>
    <% set Header %>
        <h1>Hello world</h1>
    <% end_set %>
    <% set Body %>
       <% include AnotherTemplateName %>
    <% end_set %>
<% end_template %>
```

in AnotherTemplateName  you can

```
        <% template AnotherTemplateName %>
            <% set AnotherHeader %>
                <h2>Hello world</h2>
            <% end_set %>
        <% end_template %>
```

**Comment by satrun77** [comment]
@rasstislav I have created a draft PR that may solve your issue. I have not tested with different use cases other than the one in the issue here.

**Comment by satrun77** [comment]
@rasstislav release 2.1.0 has this feature. 

Fix in https://github.com/satrun77/silverstripe-template-tags/pull/7

**Comment by rasstislav** [comment]
@satrun77 Um, I'm thinking. Is it possible to add this fix for silverstripe version 4 as well?

**Comment by satrun77** [comment]
> @satrun77 Um, I'm thinking. Is it possible to add this fix for silverstripe version 4 as well?

I don't think this is part of the road map.

**Comment by satrun77** [comment]
@rasstislav I will correct few thing in the release it should be release 2.1.0
